### ISSUE TITLE
Unable to build aarch64-unknown-linux-gnu target

### ISSUE THREAD

**Issue by joelchen** [tangramdotdev/tangram#82]
`cargo build --release` with the latest master branch of tangram on AArch64 architecture will fail with the error:
```
error: could not compile `tangram_dev`

Caused by:
  process didn't exit successfully: `rustc --crate-name tangram_dev --edition=2021 crates/dev/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C metadata=5127925cb15b9122 -C extra-filename=-5127925cb15b9122 --out-dir /home/ubuntu/tangram/target/release/deps -L dependency=/home/ubuntu/tangram/target/release/deps --extern clap=/home/ubuntu/tangram/target/release/deps/libclap-23bfe18d31f92ad3.rlib --extern sunfish=/home/ubuntu/tangram/target/release/deps/libsunfish-d04b16249dcff1ef.rlib --extern tokio=/home/ubuntu/tangram/target/release/deps/libtokio-df6922999aa345c4.rlib` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
error: build failed
```
Rust target and toolchain for AArch64 are installed:
```
$ rustup show
Default host: aarch64-unknown-linux-gnu
rustup home:  /home/ubuntu/.rustup

installed targets for active toolchain
--------------------------------------

aarch64-unknown-linux-gnu
wasm32-unknown-unknown

active toolchain
----------------

stable-aarch64-unknown-linux-gnu (default)
rustc 1.57.0 (f1edd0429 2021-11-29)
```
Machine is ARM64 based Ubuntu:
```
$ uname -a
Linux ip-10-0-0-13 5.13.0-1005-aws #6-Ubuntu SMP Fri Oct 8 07:40:12 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by nitsky** [comment]
Hi @joelchen we are able to successfully build for aarch64-unknown-linux-gnu. Based on the error message I believe the compiler is running out of memory. Are you running the compile on a resource constrained machine or in a docker container?

**Comment by joelchen** [comment]
@nitsky I am running it on an AWS t4g.micro instance.

**Comment by nitsky** [comment]
t4g.micro instances have only 1GB of memory. You will definitely need more. You can try it with 4GB but I suggest at least 8GB.

**Comment by joelchen** [comment]
Thank you, it works with 4GB. If I remove Cargo.lock I get the following errors:
```
   Compiling tree-sitter-highlight v0.19.2
error[E0107]: this struct takes 2 lifetime arguments but 1 lifetime argument was supplied
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tree-sitter-highlight-0.19.2/src/lib.rs:104:30
    |
104 |     captures: iter::Peekable<QueryCaptures<'a, &'a [u8]>>,
    |                              ^^^^^^^^^^^^^ -- supplied 1 lifetime argument
    |                              |
    |                              expected 2 lifetime arguments
    |
note: struct defined here, with 2 lifetime parameters: `'a`, `'tree`
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tree-sitter-0.20.2/binding_rust/lib.rs:152:12
    |
152 | pub struct QueryCaptures<'a, 'tree: 'a, T: TextProvider<'a>> {
    |            ^^^^^^^^^^^^^ --  -----
help: add missing lifetime argument
    |
104 |     captures: iter::Peekable<QueryCaptures<'a, 'a, &'a [u8]>>,
    |                                              ++++

error[E0107]: this struct takes 2 lifetime arguments but 1 lifetime argument was supplied
    --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tree-sitter-highlight-0.19.2/src/lib.rs:1028:19
     |
1028 |     query_match: &QueryMatch<'a>,
     |                   ^^^^^^^^^^ -- supplied 1 lifetime argument
     |                   |
     |                   expected 2 lifetime arguments
     |
note: struct defined here, with 2 lifetime parameters: `'cursor`, `'tree`
    --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tree-sitter-0.20.2/binding_rust/lib.rs:134:12
     |
134  | pub struct QueryMatch<'cursor, 'tree> {
     |            ^^^^^^^^^^ -------  -----
help: add missing lifetime argument
     |
1028 |     query_match: &QueryMatch<'a, 'a>,
     |                                ++++

For more information about this error, try `rustc --explain E0107`.
error: could not compile `tree-sitter-highlight` due to 2 previous errors
```

**Comment by nitsky** [comment]
@joelchen our Cargo.lock has to pin the version of the tree-sitter crate to v0.19.5 because the tree-sitter-highlight crate at v0.19.2 depends on it like so:

```
[dependencies.tree-sitter]
version = ">= 0.3.7"
```

Now that tree-sitter v0.20.0 has been released, the only way to keep tree-sitter at v0.19.5 is with the Cargo.lock. This issue will be resolved when we upgrade to v0.20.
